import localFont from "next/font/local";
import "@/styles/reset.scss";
import "@/styles/global.scss";
import {
  ScrollProvider,
} from "@/lib/providers/ScrollProvider/ScrollProvider";
import Header from "@/utils/Header/Header";
import Footer from "@/utils/Footer/Footer";
import { LocaleProvider } from "@/lib/providers/LocaleContext/LocaleContext";
import ContactForm from "@/utils/ContactForm/ContactForm";

const ppMori = localFont({
  src: [
    {
      path: "./fonts/PPMori/PPMori-SemiBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/PPMori/PPMori-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--pp-mori",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="html">
      <body className={`${ppMori.variable} body`}>
        <ScrollProvider scrollBar></ScrollProvider>
        <LocaleProvider>
          <Header />
          {children}
          <ContactForm />
          <Footer />
        </LocaleProvider>
      </body>
    </html>
  );
}
